Repository FiveD-SE/ResortManagementSystem-BE, pull requests merged in 2024-12, with the labels that each got.

#25 feat: calculate total amount based on the number of nights for bookings
  src/modules/booking/booking.service.ts
Labels: enhancement

#26 feat: implement email sending functionality and update booking service for improved data handling
  src/modules/booking/booking.service.ts
  src/modules/email/dto/sendEmail.dto.ts
  src/modules/email/email.controller.ts
  src/modules/email/email.module.ts
  src/modules/email/email.service.ts
  src/modules/room/room.service.ts
Labels: bug, enhancement

#30 fix: convert room ID to string format in room service
  src/modules/room/room.service.ts
Labels: bug

#34 refactor: add endpoint to retrieve yearly revenue data in Admin Dashboard
  src/modules/admin-dashboard/admin-dashboard.controller.ts
Labels: bug

#37 feat: enhance booking service with transfer invoice creation and paym…
  src/modules/booking/booking.service.ts
  src/modules/booking/dto/createBooking.dto.ts
  src/modules/booking/entities/booking.entity.ts
  src/modules/invoice/dto/createInvoice.dto.ts
  src/modules/user/user.controller.ts
Labels: enhancement

#38 fix: ensure promotionId defaults to null if not provided
  src/modules/booking/booking.service.ts
Labels: bug
